imports:
    - { resource: config.yml }

parameters:
    command:
        App\Main\Command: %kernel.root_dir%/../src/App/Main/Command
        Yarik\MicroSymfony\Command: %kernel.framework_dir%/Command
