imports:
    - { resource: parameters.yml }
    - { resource: components.yml }

services:
    app.container_wrapper:
        class: App\Main\Container\ContainerWrapper
        arguments: [@container]
