#!/usr/bin/env php
<?php

const WEB_DIR = __DIR__;
//require_once __DIR__ . '/cache.php';
require_once __DIR__ . '/../vendor/autoload.php';

$time = microtime(true) * 1000;
require_once __DIR__ . '/AppKernel.php';

//$kernel = new \Cache\CacheKernel(null);
$kernel = new AppKernel('command');
$input = new \Yarik\MicroSymfony\Component\Console\ArgvInput();

$console = new \Yarik\MicroSymfony\Component\Console\Console($kernel->getContainer());
$console->initCommands();
$console->run($input);

var_dump(microtime(true) * 1000 - $time);
